[tasks.fmt]
description = "Run formatter"
command = "nix"
args = ["fmt"]

[tasks.update]
script = '''
  nix flake update
  '''

[tasks."aarch64-darwin:desktop"]
script = '''
  sudo darwin-rebuild switch --flake .#desktop --override-input user-config path:./user.nix
'''

[tasks."aarch64-darwin:work"]
script = '''
  sudo darwin-rebuild switch --flake .#work --override-input user-config path:./user.nix
'''
