[settings]
idiomatic_version_file_enable_tools = ['node', 'java']

[tools]
node = '22'

"npm:yarn" = "latest"
"npm:pnpm" = "latest"

"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:bun" = "latest"

"npm:pure-prompt" = "latest"

java = '17'
