{ ... }:

{
  imports = [
    ../../programs/commands/coreutils.nix
    ../../programs/commands/git
    ../../programs/commands/fzf
    ../../programs/commands/ghq.nix
    ../../programs/commands/eza.nix
    ../../programs/commands/bat.nix
    ../../programs/commands/hurl.nix
    ../../programs/commands/ripgrep.nix
    ../../programs/commands/fd.nix
    ../../programs/commands/tree.nix
    ../../programs/commands/bottom.nix
    ../../programs/commands/jq.nix
    ../../programs/commands/tig
    ../../programs/commands/sd.nix
    ../../programs/commands/zoxide.nix
    ../../programs/commands/cargo-make.nix
    ../../programs/commands/kustomize.nix
    ../../programs/commands/gh.nix
    ../../programs/commands/gh-dash.nix
    ../../programs/commands/ditaa.nix
    ../../programs/commands/cmigemo.nix
    ../../programs/commands/gnupg.nix
    ../../programs/commands/ast-grep.nix
    ../../programs/commands/hexyl.nix
    ../../programs/commands/delta.nix
    ../../programs/commands/hugo.nix
    ../../programs/commands/textlive.nix
    ../../programs/commands/jnv.nix
    ../../programs/commands/atuin.nix
    ../../programs/commands/sheldon
    ../../programs/commands/fzy.nix
    ../../programs/commands/tbls.nix
    ../../programs/commands/jd-diff-patch.nix
    ../../programs/commands/ni.nix
  ];
}
