{ ... }:

{
  imports = [
    ../../programs/coreutils.nix
    ../../programs/git
    ../../programs/fzf
    ../../programs/ghq.nix
    ../../programs/eza.nix
    ../../programs/bat.nix
    ../../programs/hurl.nix
    ../../programs/ripgrep.nix
    ../../programs/fd.nix
    ../../programs/tree.nix
    ../../programs/bottom.nix
    ../../programs/jq.nix
    ../../programs/tig
    ../../programs/sd.nix
    ../../programs/zoxide.nix
    ../../programs/cargo-make.nix
    ../../programs/kustomize.nix
    ../../programs/gh.nix
    ../../programs/gh-dash.nix
    ../../programs/ditaa.nix
    ../../programs/cmigemo.nix
    ../../programs/gnupg.nix
    ../../programs/ast-grep.nix
    ../../programs/hexyl.nix
    ../../programs/delta.nix
    ../../programs/hugo.nix
    ../../programs/textlive.nix
    ../../programs/jnv.nix
    ../../programs/atuin.nix
    ../../programs/sheldon
    ../../programs/fzy.nix
    ../../programs/tbls.nix
    ../../programs/jd-diff-patch.nix
    ../../programs/ni.nix
  ];
}
