[
  ../modules/homebrew/1password.nix
  ../modules/homebrew/aerospace.nix
  ../modules/homebrew/alt-tab.nix
  ../modules/homebrew/aquaskk.nix
  ../modules/homebrew/brave-browser.nix
  ../modules/homebrew/codexbar.nix
  ../modules/homebrew/gas-mask.nix
  ../modules/homebrew/google-chrome.nix
  ../modules/homebrew/intellij-idea.nix
  ../modules/homebrew/lmstudio.nix
  ../modules/homebrew/rancher.nix
  ../modules/homebrew/raycast.nix
  ../modules/homebrew/rtk.nix
  ../modules/homebrew/vscode.nix
]
